// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://pgywtjfdnefegeyahhij.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneXd0amZkbmVmZWdleWFoaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDUwMjUsImV4cCI6MjA2NTI4MTAyNX0.ndoyr1XkUuf3KcoHs6G5NlLShj996Vbj0tJRKEYxez0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);